name: Product Catalog CI
permissions:
  contents: write
  id-token: none

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/workflow-reusable.yml
