name: Feature Branch CI

on:
  push:
    branches-ignore:
      - development
      - master

  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/workflow-reusable.yml
    with:
      mode: ci
