name: Publish to Azure DevOps Artifacts

on:
  push:
    branches:
      - development
      - main

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Add Azure Artifacts feed
        run: |
          dotnet nuget add source \
            "https://pkgs.dev.azure.com/${{ secrets.ADO_ORG_NAME }}/${{ secrets.ADO_PROJECT_NAME }}/_packaging/${{ secrets.ADO_FEED_NAME }}/nuget/v3/index.json" \
            --name AzureArtifacts \
            --username github \
            --password ${{ secrets.AZURE_DEVOPS_PAT }} \
            --store-password-in-clear-text
    
      - name: Authenticate to Azure DevOps Artifacts
        run: |
         echo 'VSS_NUGET_EXTERNAL_FEED_ENDPOINTS={"endpointCredentials":[{"endpoint":"https://pkgs.dev.azure.com/ORG_NAME/_packaging/ADO_FEED_NAME/nuget/v3/index.json","username":"github","password":"${{ secrets.AZURE_DEVOPS_PAT }}"}]}' >> $GITHUB_ENV

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack --configuration Release --no-build -o nupkg

      - name: Push package to Azure DevOps Artifacts
        run: |
          dotnet nuget push "nupkg/*.nupkg" \
          --source "https://pkgs.dev.azure.com/ORG_NAME/_packaging/ADO_FEED_NAME/nuget/v3/index.json" \
          --skip-duplicate

