name: GitHub action reusable workflow

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    secrets:
      AD_TENANT_ID:
        description: 'Azure Enterprise Application (client) ID'
        required: false
      AD_CLIENT_ID:
        description: 'Azure Enterprise Directory (tenant) ID'
        required: true
      ADO_ORG_NAME:
        description: 'Azure DevOps Organization Name'
        required: true
      ADO_PROJECT_NAME:
        description: 'Azure DevOps Project name'
        required: true
      ADO_FEED_NAME:
        description: 'Azure DevOps Feed name'
        required: true

env:
  PUBLISH_DIR: publish
  PROJ_WORK_DIR: Catalogs
  PROJ_FILE_NAME: Catalogs.csproj
  ENABLE_TEST: true

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate-sem-ver.outputs.version }}
      branch_name: ${{ steps.generate-sem-ver.outputs.branch_name }}
      pkg_description: ${{ steps.generate-sem-ver.outputs.pkg_description }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            ${{ env.PROJ_WORK_DIR }}/${{ env.PROJ_FILE_NAME }}

      - name: Generate semantic version
        id: generate-sem-ver
        uses: danielhagos11/DevOps/dotnet-build@main
        with:       
          version_file: ${{ env.PROJ_WORK_DIR }}/${{ env.PROJ_FILE_NAME }}

  build:
    runs-on: ubuntu-latest
    needs: [semver]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: danielhagos11/DevOps/dotnet-build@main
        with:
          proj_work_dir: ${{ env.PROJ_WORK_DIR }}
          proj_file_name: ${{ env.PROJ_FILE_NAME }}
          enable_test: ${{ env.ENABLE_TEST }}
          publish_args: -p:PublishSingleFile=true -p:PublishReadyToRun=true

      - name: Upload publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.semver.outputs.version }}
          path: ${{ github.workspace }}/${{ env.PUBLISH_DIR }}
          retention-days: 60

  publish:
    runs-on: ubuntu-latest
    needs: [semver, build]
    steps:
      - name: Fetch actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.semver.outputs.version }}*
          path: ${{ github.workspace }}/artifact

      - name: Zip folders
        uses: danielhagos11/DevOps/zip-folders@c30137135f2360757dffe9bd032c27d64aa529f2
        with:
          working_directory: ${{ github.workspace }}/artifact
